### ISSUE TITLE
With libc++1-8 std::string is out of date in pretty printers.

### ISSUE THREAD

**Issue by ericwomer** [koutheir/libcxx-pretty-printers#5]
When displaying or printing std::strings I now  get this error (Note executable_name is a std::string)
```
 (gdb) print executable_name
 $2 = Python Exception <class 'gdb.error'> There is no member or method named __first_.:

```

in my .gdbinit file
```
# libc++ gdb pretty printers
python
import sys 
sys.path.insert(0, '/home/rake/src/Tools/libcxx-pretty-printers/src') 
from libcxx.v1.printers import register_libcxx_printers 
register_libcxx_printers (None) 
end
```

and building with these c/cppflags enabled
```
-D_LIBCPP_DEBUG=1 -g -O0
```

Disabling libcxx pretty printers I get
```
(gdb) print executable_name
$2 = {<std::__1::__basic_string_common<true>> = {<No data fields>}, static __short_mask = 1, static __long_mask = 1, 
  __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {__value_ = {{__l = {__cap_ = 81, 
            __size_ = 73, __data_ = 0x60f800 "/home/rake/src/Pluralsight/PracticalCppFeatures/build/PractialCppFeatures"}, __s = {{__size_ = 81 'Q', __lx = 81 'Q'}, 
            __data_ = "\000\000\000\000\000\000\000I\000\000\000\000\000\000\000\000\370`\000\000\000\000"}, __r = {__words = {81, 73, 
              6354944}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}
```

And strangely enough in lldb I get 
```
print executable_name
(std::__1::string) $1 = "/home/rake/src/Pluralsight/PracticalCppFeatures/build/PractialCppFeatures"
```

They both show the correct data but one is a garbled mess of information.

**Comment by koutheir** [comment]
Thank you for reporting the issue. I will try to look at it as soon as I have some spare time.

**Comment by Narendar542** [comment]
--- a/src/libcxx/v1/printers.py
+++ b/src/libcxx/v1/printers.py
@@ -61,21 +61,22 @@ class StdStringPrinter:
         self.typename = typename

     def to_string(self):
-        # Make sure &string works, too.
-        type = self.val.type
-        if type.code == gdb.TYPE_CODE_REF:
-            type = type.target()
-
-        ss = self.val['__r_']['__first_']['__s']
-        __short_mask = 0x1
-        if (ss['__size_'] & __short_mask) == 0:
-            len = (ss['__size_'] >> 1)
-            ptr = ss['__data_']
-        else:
-            sl = self.val['__r_']['__first_']['__l']
-            len = sl['__size_']
-            ptr = sl['__data_']
-
+        try:
+           type = self.val.type
+           if type.code == gdb.TYPE_CODE_REF:
+               type = type.target()
+
+           ss = self.val['__r_']['__value_']['__s']
+           __short_mask = 0x1
+           if (ss['__size_'] & __short_mask) == 0:
+               len = (ss['__size_'] >> 1)
+               ptr = ss['__data_']
+           else:
+               sl = self.val['__r_']['__value_']['__l']
+               len = sl['__size_']
+               ptr = sl['__data_']
+        except  Exception as e:
+           return ""

**Comment by koutheir** [comment]
@salamanderrake, could you please check if the recent merge solves this issue?
