### ISSUE TITLE
No pretty printers working on Linux

### ISSUE THREAD

**Issue by abrownsword** [koutheir/libcxx-pretty-printers#9]
I'm trying to get this project working on an AAarch64 Ubuntu 18.04 system while remote debugging with CLion 2019.2.  Alas it isn't.

From the debugger's log output, the libc++ pretty printers seem to be installed.  When trying to view variables that should use them, however, I get just the basic type information.  One thing I notice, which I'm not sure if it is a problem, is that the pretty printers info says they are all in the std:: namespace, whereas while trying to view types, all the types are in the std::__1:: namespace.  Is this an issue?

Any other suggestions for things to try?

**Comment by koutheir** [comment]
> the pretty printers info says they are all in the std:: namespace

Where did you see this information?

**Comment by abrownsword** [comment]
In the debugger's log.  Here it is (pruned of unuseful per line prefixes):

<(gdb) 
>info pretty-printer 
<&"info pretty-printer\n" 
<~"global pretty-printers:\n" 
<~"  builtin\n" 
<~"    mpx_bound128\n" 
<~"  libc++\n" 
<~"    std::__bit_iterator\n" 
<~"    std::__deque_iterator\n" 
<~"    std::__hash_const_iterator\n" 
<~"    std::__hash_iterator\n" 
<~"    std::__hash_map_const_iterator\n" 
<~"    std::__hash_map_iterator\n" 
<~"    std::__list_const_iterator\n" 
<~"    std::__list_iterator\n" 
<~"    std::__map_const_iterator\n" 
<~"    std::__map_iterator\n" 
<~"    std::__tree_const_iterator\n" 
<~"    std::__tree_iterator\n" 
<~"    std::__wrap_iter\n" 
<~"    std::basic_string\n" 
<~"    std::bitset\n" 
<~"    std::deque\n" 
<~"    std::forward_list\n" 
<~"    std::list\n" 
<~"    std::map\n" 
<~"    std::multimap\n" 
<~"    std::multiset\n" 
<~"    std::pair\n" 
<~"    std::priority_queue\n" 
<~"    std::queue\n" 
<~"    std::set\n" 
<~"    std::shared_ptr\n" 
<~"    std::stack\n" 
<~"    std::tuple\n" 
<~"    std::unique_ptr\n" 
<~"    std::unordered_map\n" 
<~"    std::unordered_multimap\n" 
<~"    std::unordered_multiset\n" 
<~"    std::unordered_set\n" 
<~"    std::vector\n" 
<~"    std::weak_ptr\n" 
<^done 
<(gdb)

**Comment by koutheir** [comment]
I believe that these types are only indicative of the families of STL types that are supported by the pretty printer. For example, during initialization of the pretty printer, the [line](https://github.com/koutheir/libcxx-pretty-printers/blob/9eb1bc3070a6560e388803af657b60015cfb440c/src/libcxx/v1/printers.py#L1003):
```
    printer.add('basic_string', StringPrinter)
```
invokes the function  [`add()`](https://github.com/koutheir/libcxx-pretty-printers/blob/9eb1bc3070a6560e388803af657b60015cfb440c/src/libcxx/v1/printers.py#L858) which appends a regular expression matcher for the provided type (here `basic_string`) to [`self.lookup`](https://github.com/koutheir/libcxx-pretty-printers/blob/9eb1bc3070a6560e388803af657b60015cfb440c/src/libcxx/v1/printers.py#L861). The regex used for the matcher is the following:
```
'^std::__[a-zA-Z0-9]+::basic_string<.*>$'
```
and that regex actually matches all templated variants of `std::__1::basic_string` when the pretty printer is called by GDB through the [`__call__`](https://github.com/koutheir/libcxx-pretty-printers/blob/9eb1bc3070a6560e388803af657b60015cfb440c/src/libcxx/v1/printers.py#L874).

Therefore, I don't believe this is the issue you're facing. Still, thank you for reporting this issue. I am keeping it open until I or someone else could figure out what the problem is, and hopefully solve it.

**Comment by abrownsword** [comment]
Okay, I guess that's good news.  Here is an example of the debugger output when trying to display a string variable (named cwd):

>0-interpreter-exec --thread 1 --frame 0 mi2 "-var-create var45_cwd * \"cwd\"" 
<^done,name="var45_cwd",numchild="0",value="{...}",type="std::__1::string",thread-id="1",has_more="0" 
<0^done 

The debugger ui isn't showing a value, which I assume is a result of getting "{...}" back from gdb.

**Comment by abrownsword** [comment]
Have been trying to dig into this again recently, and found that in gdb when I try to print a std::string, I get this:

`Python Exception <class 'gdb.error'> There is no member named __r_.: `

More interesting though, is that ff I disable pretty-printer then I get this:

`$1 = <incomplete type>`

Any thoughts @koutheir ?

**Comment by koutheir** [comment]
Thank you for the analysis. This means that there has been another change in the internal structure of `std::basic_string` in `libc++`. The error likely originates in [`StringPrinter.to_string()`](https://github.com/koutheir/libcxx-pretty-printers/blob/9eb1bc3070a6560e388803af657b60015cfb440c/src/libcxx/v1/printers.py#L141). This requires changes to the code to adapt to the new implementation details. Pull requests are welcome!

**Comment by abrownsword** [comment]
I’m not convinced.  I inspected my std::basic_string declaration and it seems to have __r_.  This is why I think the message when the pretty printers are disabled is particularly interesting.  Might be a symbol resolution issue?

**Comment by abrownsword** [comment]
I defined  `-D_LIBCPP_DEBUG=1` and now I'm getting this with pretty-printer:

`$1 = StringPrinter.to_string
Python Exception <class 'NameError'> name 'unichr' is not defined: `

And this without:

`$2 = {<std::__1::__basic_string_common<true>> = {<No data fields>}, static __short_mask = 1, static __long_mask = 1, 
  __r_ = {<std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>> = {
      __value_ = {{__l = {__cap_ = 549755811064, __size_ = 549755811480, 
            __data_ = 0xa40c1c <std::__1::forward_as_tuple<std::__1::allocator<CLI::detail::Number::Number()::{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)#1}> const&>(std::__1::allocator<CLI::detail::Number::Number()::{lambda(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)#1}> const&)+52> "\350\a", <incomplete sequence \371>}, __s = {{__size_ = 248 '\370', 
              __lx = 248 '\370'}, __data_ = "\364\377\377\177\000\000\000\230\366\377\377\177\000\000\000\034\f\244\000\000\000\000"}, __r = {__words = {
              549755811064, 549755811480, 
              10751004}}}}}, <std::__1::__compressed_pair_elem<std::__1::allocator<char>, 1, true>> = {<std::__1::allocator<char>> = {<No data fields>}, <No data fields>}, <No data fields>}, static npos = 18446744073709551615}`

**Comment by mahhov** [comment]
I had a similar issue, but replacing `unichr` with `chr` in `libcxx-pretty-printers/printers.py` fixed it in my case.

**Comment by Macfly** [comment]
this PRfix the issue:
https://github.com/koutheir/libcxx-pretty-printers/pull/10
